### ISSUE TITLE
{{# each in}} context variables not printing 

### ISSUE THREAD

**Issue by samueljoos** [timbrandin/meteor-sideburns#11]
Hi,

First of all love the concept of this package.
Second I am having some troubles getting an "each in" loop to work. 
It Iterates through my mongo collection but {{ item.text }} isn't printed. 

example:
```javascript
<template name="Page">
<div>
    <h1>{{test}}</h1>
    <ul>
        {{#each item in getItems}}
        <li>{{item.text}}</li>
        {{/each}}
    </ul>
</div>
</template>

Template.Page.onCreated(function() {
  this.name = new ReactiveVar('foo');
  this.items = People.find();
});

Template.Page.helpers({
    getItems(){
        return this.items.fetch();
    },
    test(){
        return this.name.get();
    }
})

Template.Page.events({
  'click .test': function() {
    this.name.set("bar");
  }
});
```

The reactivevar is showing up perfectly so it must be somethings specific to "each in" loops. 
I'll try to investigate your package myself but any help would be great :).

**Comment by samueljoos** [comment]
Hi Tim,

As you can see I found a way to fix the issue. Just ask if you have any questions or need help with my pull request. I am actively using this package in a personal project and it's working pretty good. I might add a couple of new pull requests in the future though ;)

**Comment by timbrandin** [comment]
This is great! I've commented on your PR, it looks good, but needs an update as I merged your other PR yesterday. :+1:
