### ISSUE TITLE
Using Sideburns with Jade

### ISSUE THREAD

**Issue by brajt** [timbrandin/meteor-sideburns#17]
I'm wondering, what solution would you recommend for making Sideburns work with [meteor-jade](https://github.com/mquandalle/meteor-jade) package? Would that even be possible or is it too many abstraction layers to be worth implementing?

**Comment by timbrandin** [comment]
It might be to many levels of abstractions as you say, but I'm sure you could skip some of them by just doing jade to react directly with a new extension, or use .jade but warn about using both packages at the same time. :+1:

**Comment by brajt** [comment]
Thanks a lot, I'll try that!
