### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by j20** [timbrandin/meteor-sideburns#21]
This looks amazing. A few questions that aren't covered in the ReadMe and maybe could be.

Will this be any slower than plain React itself? Or is this simply syntactic sugar that gets converted into React's normal syntax using Meteor's build pipeline?

When sideburns is fully developed, will it have any notable limitations compared to using regular React? And if so, is it possible to use regular React syntax for some components and sideburns for others in the same project?

**Comment by timbrandin** [comment]
It gets converted into React.

One should always be able to pull out the React versions of things. :+1:

And, right now one can use regular React together with this. It only finds what it recognizes and converts it into React syntax.

**Comment by j20** [comment]
Fantastic. Thanks!

**Comment by timbrandin** [comment]
And yes, this is basically just a build step plus some code to help React with some issues like allowing for undefined variables in templates and also cleaning output to htmlentities like Blaze already does.
