### ISSUE TITLE
Support for onRendered()

### ISSUE THREAD

**Issue by patrickml** [timbrandin/meteor-sideburns#4]
I believe the react equivalent to onRendered is `componentDidMount` so is this something we could append to `getMeteorData` or something during compilation?

**Comment by timbrandin** [comment]
Hey, check the devel branch, I've tested using 
```
Template.Example.extend({
  componentDidMount: function() {
    // Do client side stuff (jQuery etc).
  }
});
```

**Comment by timbrandin** [comment]
But I was talking to a coworker about this, and it would be much nicer to support this instead, but also onRendered for backwards compatibility for Blaze templates.

```
Template.Example.componentDidMount = function() {
  // Do client side stuff (jQuery etc).
};

// or this way. But we could allow for both ways, but the above would imply only one method is called and overwrite any other method added through the below method).

Template.Example.onComponentDidMount(function() {
  // Do client side stuff (jQuery etc).
});
```

**Comment by patrickml** [comment]
Agreed it would be nice. I also do agree with both using extend (incase react adds something new) as well as adding functions like you said

~~~
Template.Name.onComponentDidMount(function() {
  // Do client side stuff (jQuery etc).
});
~~~

Since react has many event functions such as `componentWillReceiveProps` which currently I am implementing like so 

~~~
Template.Example.onCreated(function () {
  var component = this;
  component.componentWillReceiveProps = function () {
//code
  };

component.componentDidMount = function () {
//code
});

~~~

Doing so will allow us to separate each event listener into a clean fashion. I would love to help you out with this. How far are you in achieving this?

**Comment by timbrandin** [comment]
I've only updated the Readme on this branch https://github.com/timbrandin/meteor-react-jsx-templating/tree/feature-template-events, mostly to get a feel of how the API would work and be implemented. Feel free to fork from that branch.

Plus, what do you think of renaming this project to Sideburns?

**Comment by patrickml** [comment]
I like it. If we get enough community support hopefully it can replace blaze with simply the add of a package. Also I thinking about how the compiler works atm. Currently it concatenates strings into the resulting function but why cant we create a json config object `let reactConfig = {}` and append data like `reactConfig.displayName = className` and so on for all functions and such and then do `reactConfig.toString()` in order to get the string and then all you have to do is concat the `React.createClass(` and now you can leverage javascript and only adding objects if they are needed such as events only if there are events.

**Comment by timbrandin** [comment]
Ah, that's how you do it. Alright! I was looking for that.

I was mainly focusing on getting to a MVP that does the work, then we can reconstruct things and add tests.

**Comment by timbrandin** [comment]
Oh and we need some way of doing source mapping to the users original file, so that we can help them debug their code. Now it's kind of hard to debug without printing out the compiled version.

**Comment by patrickml** [comment]
Sadly I don't know anything about that but I'm sure someone who jumps on
this project will. Look into zen hub we use it at work for issue tracking I
since it integrates directly with githubs website what do you think about
using it for this project for issues?

**Comment by timbrandin** [comment]
feel free to set it up. :)

**Comment by patrickml** [comment]
@timbrandin in order for me to set up zenhub for the project I have to have access rights to the repository.

**Comment by timbrandin** [comment]
@patrickml you should be all set now :)
